global:
  scrape_interval: 10s

scrape_configs:
- job_name: vmagent
  static_configs:
  - targets:
    - vmagent:8429
  metric_relabel_configs:
  - source_labels: [name]
    regex: 'e.*'
    action: drop
- job_name: vmauth
  static_configs:
  - targets:
    - vmauth:8427
  bearer_token_file: ./metric.txt
- job_name: vmalert
  static_configs:
  - targets:
    - vmalert:8880
- job_name: vminsert
  static_configs:
  - targets:
    - vminsert-1:8480
    - vminsert-2:8480
- job_name: vmselect
  static_configs:
  - targets:
    - vmselect-1:8481
    - vmselect-2:8481
- job_name: vmstorage
  static_configs:
  - targets:
    - vmstorage-1:8482
    - vmstorage-2:8482
